# using shared Shell runner with Java 21
variables:
  JAVA_HOME: "/usr/lib/jvm/temurin-21-jdk-amd64"
  DOCKER_SECURITY_OPT: seccomp=unconfined # quick fix for docker problems (should update docker in CI instead!)
default:
  tags:
    - shared

stages:
  - build
  - test
  - deploy

mvn-build:
  stage: build
  script:
    - java --version
    - echo $JAVA_HOME
    - mvn package -DskipTests
    - docker build -t sample-agent-container-image examples/sample-container/

mvn-test:
  stage: test
  script:
    - mvn test

mvn-deploy:
  stage: deploy
  only:
    - main
  script:
    - mvn deploy -DskipTests
