stages:
  - build
  - test
  - deploy

default:
  tags:
    - shared

mvn-build:
  stage: build
  script:
    - mvn compile

mvn-test:
  stage: test
  script:
    - mvn test

# deployment is skipped for now
.mvn-deploy:
  stage: deploy
  only:
    - master
  script:
    - mvn deploy
