# using shared Shell runner with Java 17
variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
default:
  tags:
    - shared

stages:
  - build
  - test
  - deploy

mvn-build:
  stage: build
  script:
    - mvn compile

mvn-test:
  stage: test
  script:
    - mvn test

mvn-deploy:
  stage: deploy
  only:
    - main
  script:
    - mvn deploy -DskipTests
