stages:
  - build
  - test
  - deploy

image: maven:3.8.5-openjdk-17

mvn-build:
  stage: build
  script:
    - mvn compile

mvn-test:
  stage: test
  script:
    - mvn test

# deployment is skipped for now
.mvn-deploy:
  stage: deploy
  only:
    - master
  script:
    - mvn deploy
