version: "3.3"

services:

  runtime-platform:
    image: jiacpp-platform
    build: .
    ports:
      - "8000:8000"
    # for running containers on the same Docker as the platform itself
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

