version: "3.3"

# This docker-compose is specifically for running unit tests, otherwise you would usually not start two
# runtime platforms on the same hosts. Can be used as a template for actual RP docker-compose file though.

services:

  runtime-platform-1:
    image: jiacpp-platform
    build:
      .
    ports:
      - 8001:8000
    # run containers on the same Docker as the platform itself
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runtime-platform-2:
    image: jiacpp-platform
    build:
      .
    ports:
      - 8002:8000
    # run containers on the same Docker as the platform itself
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
