package de.gtarc.opaca.container

import com.fasterxml.jackson.databind.JsonNode
import de.gtarc.opaca.model.AgentDescription
import de.gtarc.opaca.model.Login

// Messages for Registering an Agent with the Container Agent (or updating an already registered agent)
// and for de-registering an agent. Those just wrap one other element each, but may still be useful for
// more "meaningful" messages sent to and received by the ContainerAgent.

data class Register(val description: AgentDescription, val notify: Boolean)

data class Registered(val parentUrl: String?, val containerId: String, val authToken: String?)

data class DeRegister(val agentId: String, val notify: Boolean)

// Message for informing agents about a user login. The Token is generated by the ContainerAgent and distributed to all
// agents in the container, who may choose to use or ignore it. Later, the same loginToken is sent along with Invoke
// and other messages so the respective agents can select the respective login (or cached client) for that user.

data class LoginMsg(val loginToken: String, val login: Login)

// Message for Invoking a OPACA action at a containerized agent, wrapping the name of the action to call
// and its parameters, to be handled by an invoke-ask "respond" handler.

data class Invoke(val name: String, val parameters: Map<String, JsonNode>, val loginToken: String? = null)
data class RenewToken(val value: String)

data class StreamGet(val name: String)
data class StreamPost(val name: String, val body: ByteArray)
