# GENERAL SETTINGS
server.port=${PORT:8000}
public_url=${PUBLIC_URL:#{null}}
container_environment=${CONTAINER_ENVIRONMENT:docker}
platform_environment=${PLATFORM_ENVIRONMENT:native}
session_policy=${SESSION_POLICY:shutdown}
container_timeout_sec=${CONTAINER_TIMEOUT_SEC:10}
default_image_directory=${DEFAULT_IMAGE_DIRECTORY:#{null}}
event_history_size=${EVENT_HISTORY_SIZE:50}
always_pull_images=${ALWAYS_PULL_IMAGES:false}

# SECURITY & AUTHENTICATION
security.requireAuth=${REQUIRE_AUTH:false}
security.kc_realm=${KC_REALM:null}
security.kc_clientid=${KC_CLIENT:null}

# IMAGE REGISTRY CREDENTIALS
registry_separator=${REGISTRY_SEPARATOR:;}
registry_names=${REGISTRY_NAMES:}
registry_logins=${REGISTRY_LOGINS:}
registry_passwords=${REGISTRY_PASSWORDS:}

# DOCKER (only for container_environment = "docker"
remote_docker_host=${REMOTE_DOCKER_HOST:#{null}}
remote_docker_port=${REMOTE_DOCKER_PORT:2375}

# KUBERNETES (only for container_environment = "kubernetes")
kubernetes_namespace=${KUBERNETES_NAMESPACE:agents}
kubernetes_config=${KUBERNETES_CONFIG:~/.kube/config}

# LOGGING
logging.level.de.gtarc.opaca=${LOG_LEVEL:info}
logging.file.name=opaca-platform.log


# NEW NEW NEW

# This setting specifies the Issuer URI for JWT authentication. It includes the URI of the Keycloak realm.
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KC_REALM:null}

logging.level.org.springframework.security=DEBUG
