# STANDARD SETTINGS
server.port=${PORT:8000}
logging.level.de.gtarc.opaca=${LOG_LEVEL:info}
logging.file.name=opaca-platform.log

# GENERAL SETTINGS
opaca.public_url=${PUBLIC_URL:#{null}}
opaca.container_environment=${CONTAINER_ENVIRONMENT:docker}
opaca.platform_environment=${PLATFORM_ENVIRONMENT:native}
opaca.session_policy=${SESSION_POLICY:shutdown}
opaca.container_timeout_sec=${CONTAINER_TIMEOUT_SEC:10}
opaca.default_image_directory=${DEFAULT_IMAGE_DIRECTORY:#{null}}
opaca.event_history_size=${EVENT_HISTORY_SIZE:50}
opaca.always_pull_images=${ALWAYS_PULL_IMAGES:false}

# SECURITY & AUTHENTICATION
opaca.security.requireAuth=${REQUIRE_AUTH:false}
opaca.security.kc_issuer_uri=${KC_ISSUER_URI:#{null}}
opaca.security.kc_clientid=${KC_CLIENT:#{null}}
opaca.security.kc_admin=${KC_ADMIN:#{null}}
opaca.security.kc_admin_pw=${KC_ADMIN_PW:#{null}}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KC_ISSUER_URI:#{null}}

# IMAGE REGISTRY CREDENTIALS
opaca.registry.separator=${REGISTRY_SEPARATOR:;}
opaca.registry.names=${REGISTRY_NAMES:}
opaca.registry.logins=${REGISTRY_LOGINS:}
opaca.registry.passwords=${REGISTRY_PASSWORDS:}

# DOCKER (only for container_environment = "docker"
opaca.docker.remote_host=${REMOTE_DOCKER_HOST:#{null}}
opaca.docker.remote_port=${REMOTE_DOCKER_PORT:2375}

# KUBERNETES (only for container_environment = "kubernetes")
opaca.kubernetes.namespace=${KUBERNETES_NAMESPACE:agents}
opaca.kubernetes.config=${KUBERNETES_CONFIG:~/.kube/config}
