@startuml
'https://plantuml.com/sequence-diagram

hide footbox
boundary "Web UI" as U
participant "RuntimePlatform A" as A
participant "RuntimePlatform B" as B

title Protocol for Connecting two Runtime Platforms

hnote across: "connect"

U -> A: /connect "platform-b"
A -> A: add "platform-b" to pending
A -> B: /connect "platform-a"
B -> B: add "platform-a" to pending
B -> A: /connect "platform-b"
A --> B: already in pending -> true
B -> A: /info
A --> B: platform-info
B -> B: remove from pending,\nadd to connected
B --> A: true
A -> B: /info
B --> A: platform-info
A -> A: remove from pending,\nadd to connected
A --> U: true

hnote across: "disconnect"

U -> A: /disconnect "platform-b"
A -> A: remove "platform-b" from connected
A -> B: /disconnect "platform-a"
B -> B: remove "platform-a" from connected
B -> A: /disconnect "platform-a"
A --> B: already removed -> false
B --> A: true
A --> U: true

@enduml
