@startuml connect-platform
'https://plantuml.com/sequence-diagram

hide footbox
boundary "Web UI" as U
participant "RuntimePlatform A" as A
participant "RuntimePlatform B" as B

title Protocol for Connecting two Runtime Platforms

hnote across: "connect"

U -> A: POST /connect "platform-b"
A -> B: GET /info
A <-- B: platform-info

group opt [connect back?]
    group opt [auth enabled?]
        A -> A: generate token for B
    end
    A -> B: POST /connect "platform-a"
    A <- B: GET /info
    A --> B: platform-info
    B -> B: add A to connected
    A o<- B: WS /subscribe
    A <-- B: true
end
A -> A: add B to connected
A ->o B: WS /subscribe

U <-- A: true

hnote across: "disconnect"

U -> A: DEL /connect "platform-b"
A -> A: remove B from connected
A ->x B: WS (close)
group opt [connect back?]
    A -> B: DEL /connect "platform-a"
    B -> B: remove A from connected
    A x<- B: WS (close)
    A <-- B: true
end
U <-- A: true

@enduml
