apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agents-platform-sa
  namespace: agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: agents
  name: agents-platform-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agents-platform-rolebinding
  namespace: agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agents-platform-role
subjects:
- kind: ServiceAccount
  name: agents-platform-sa