services:

  # THE MAIN OPACA RUNTIME PLATFORM RUNNING IN DOCKER
  # (Agent Containers can run in the same Docker or somewhere else)
  opaca-platform:
    build: .
    image: opaca-platform
    ports:
      - "8000:8000"
    # Environment variables with no value after ":" are taken from .env file
    environment:
      # General Settings; NOTE: PUBLIC_URL must be set for PLATFORM_ENVIRONMENT 'DOCKER'!
      PORT:
      PUBLIC_URL:
      CONTAINER_ENVIRONMENT:
      PLATFORM_ENVIRONMENT: DOCKER
      SESSION_POLICY:
      CONTAINER_TIMEOUT_SEC:
      DEFAULT_IMAGE_DIRECTORY:
      EVENT_HISTORY_SIZE:
      ALWAYS_PULL_IMAGES:
      LOG_LEVEL:
      # Security & Authentication
      REQUIRE_AUTH:
      KC_ISSUER_URI:
      KC_CLIENT:
      KC_ADMIN:
      KC_ADMIN_PW:
      # Image Registry Credentials
      REGISTRY_SEPARATOR:
      REGISTRY_NAMES:
      REGISTRY_LOGINS:
      REGISTRY_PASSWORDS:
      # Docker (only for CONTAINER_ENVIRONMENT: DOCKER)
      REMOTE_DOCKER_HOST:
      REMOTE_DOCKER_PORT:
      # Kubernetes (only for PLATFORM_ENVIRONMENT: KUBERNETES)
      KUBERNETES_NAMESPACE:
      KUBERNETES_CONFIG:
    # for running containers on the same Docker as the platform itself
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - platform

  # KEYCLOAK for Authentication (optional)

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    command: export --
    #command: start-dev
    ports:
      - "9000:8080"
    depends_on:
      - keycloak_db
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PW}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    profiles:
      - keycloak

  keycloak_db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - keycloak

volumes:
  postgres_data:
    driver: local
