package de.gtarc.opaca.api;

import de.gtarc.opaca.model.AgentContainer;
import de.gtarc.opaca.model.Login;

import java.io.IOException;

/**
 * Full API that has to be provided by OPACA Agent Containers. This includes all of the common Agents API,
 * as well as some Agent Container specific routes, that are not present (or are present, but in different form)
 * on the OPACA Runtime Platform.
 *
 * It also included the names of the different Environment Variables that are passed to the OPACA Agent Container
 * when it is started by the Runtime Platform.
 */
public interface AgentContainerApi extends AgentsApi {

    // ENVIRONMENT VARIABLES

    /** name of env var holding the container ID */
    String ENV_CONTAINER_ID = "CONTAINER_ID";

    /** name of env var holding the parent platform's URL */
    String ENV_PLATFORM_URL = "PLATFORM_URL";

    /** name of env var holding the Keycloak URL incl. the Realm (if auth is enabled, else null/empty) */
    String ENV_KEYCLOAK_URL = "KEYCLOAK_URL";

    /** name of env var holding the container's own Keycloak client-secret (the client-id is the container's own ID) (if auth is enabled, else null/empty) */
    String ENV_CLIENT_SECRET = "CLIENT_SECRET";

    /** name of the user who started the container, or "anonymous" if no user was logged in */
    String ENV_OWNER = "OWNER";

    /** which ports on the host the container's ports are mapped to, in the format "containerPort1:hostPort1,..." */
    String ENV_PORT_MAPPING = "PORT_MAPPING";


    // OTHER CONSTANTS

    /** HTTP header in which the container login token is stored (see {@link #containerLogin(Login)}) */
    String HEADER_TOKEN = "ContainerLoginToken";

    /** port where the container's REST API is expected */
    int DEFAULT_PORT = 8082;


    // AGENT CONTAINER ROUTES, in addition to those defined in AgentsApi

    /**
     * Get information on the container, to be called by the Runtime Platform after start
     *
     * REST Route: GET /info
     *
     * @return  Information on the started container
     */
    AgentContainer getContainerInfo() throws IOException;

    /**
     * Supply login credentials for the Agent Container to use in later requests. The container generates and returns
     * a token and associates that with the login credentials (or a cached client object or similar). In subsequent
     * requests (e.g. to /invoke), the same token will automatically be passed as a header by the Runtime Platform so
     * the container can use the appropriate credentials/client.
     * The token is generated by the Container-Agent, and the login request is forwarded to all agents in the Agent
     * Container; the actual login-logic (if there is any specific login-logic at all) is handled by those.
     *
     * REST: POST /login
     *
     * @param loginParams Bundles the username and password in the request body
     * @return container- and user-specific access token
     */
    String containerLogin(Login loginParams) throws IOException;

    /**
     * Log current user out of a previously logged in container.
     * The logout request is forwarded to all agents in the container which then do the actual logout on their side.
     *
     * REST: POST /logout
     *
     * @return logout successful (previously logged in)
     */
    boolean containerLogout() throws IOException;

}
