# Build as `docker build -t sample-agent-container-image .`
FROM ibm-semeru-runtimes:open-19-jdk
ADD ./target/appassembler/ /app

# use this to create ping-container: docker build -t ping-container-image .
ENTRYPOINT ["/app/bin/main-kt", "ping"]
