# Build as `docker build -t sample-agent-container-image .`
FROM ibm-semeru-runtimes:open-19-jdk
ADD ./target/appassembler/ /app

# use this to create pong-container: docker build -t pong-container-image .
ENTRYPOINT ["/app/bin/main-kt", "pong"]
